# Generated by Django 4.2.3 on 2023-08-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend1app', '0002_join'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='email', max_length=50)),
                ('password', models.CharField(default='password', max_length=20)),
            ],
        ),
    ]
